# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls_id', models.CharField(blank=True, help_text='Alphanumeric id or designation as issued by MLS', max_length=128, null=True)),
                ('mls_name', models.CharField(help_text='Business name of the MLS', max_length=500)),
                ('rets_url', models.URLField(blank=True, null=True)),
                ('business_url', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls_property_id', models.CharField(help_text='The property_id as defined by the MLS, usually an integer', max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(help_text='The required 5 digit zip code of the U.S. address for this property', max_length=5)),
                ('zip_ext', models.CharField(blank=True, help_text='The optional 4 digit ZIP+4 extension for this property', max_length=4, null=True)),
                ('mls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesnacksweb.MLS')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PropertiesCurrent',
            },
        ),
    ]
