# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2015-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default='2015-01-01'),
            preserve_default=False,
        ),
    ]
