# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 07:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0003_auto_20160120_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_listing_office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='bathrooms_full',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='bathrooms_half',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='bathrooms_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='bedrooms_full',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='bedrooms_half',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='bedrooms_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='days_on_market',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='geo_long',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='list_date',
            field=models.DateTimeField(blank=True, default='2015-01-01', null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='photo_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='rooms_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Pending'), (3, 'Sold'), (4, 'Off Market')], default=1, help_text='Choose whether this is a main section, a subsection, or a third-level section', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
