# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 15:33
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0004_auto_20160121_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1_prep_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step2_download_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step3_convert_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step4_pagegen_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step5_cleanup_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('last_step_completed', models.PositiveSmallIntegerField(default=0)),
                ('data_cycle_start', models.DateTimeField(blank=True, null=True)),
                ('data_cycle_finish', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataCycleStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.PositiveSmallIntegerField(choices=[(1, 'Prepare data cycle with pre-download steps'), (2, 'Download/extract all real estate data & media'), (3, 'Normalize all downloaded data into tables'), (4, 'Generate all front-end pages and assets'), (5, 'Finish post-processing cleanup tasks')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('step_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step_start', models.DateTimeField(blank=True, null=True)),
                ('step_finish', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesnacksweb.DataCycle')),
            ],
        ),
        migrations.AlterField(
            model_name='propertycurrent',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.date(2015, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='propertycurrent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Pending'), (3, 'Sold'), (4, 'Off Market')], default=1, help_text='For sale / sold status of the property', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
