# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0006_auto_20160126_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 26, 20, 38, 10, 577984, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 26, 20, 38, 19, 935319, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
