# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0008_auto_20160126_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='data_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homesnacksweb.DataCycle'),
        ),
    ]
