# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0009_propertycurrent_data_cycle_id'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='propertycurrent',
            index_together=set([('mls', 'mls_property_id')]),
        ),
    ]
