# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0010_auto_20160203_1023'),
    ]

    operations = [

    ]
