# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls_id', models.CharField(blank=True, help_text='Alphanumeric id or designation as issued by MLS', max_length=128, null=True)),
                ('mls_name', models.CharField(help_text='Business name of the MLS', max_length=500)),
                ('rets_url', models.URLField(blank=True, null=True)),
                ('business_url', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls_property_id', models.CharField(help_text='The property_id as defined by the MLS, usually an integer', max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(help_text='The required 5 digit zip code of the U.S. address for this property', max_length=5)),
                ('zip_ext', models.CharField(blank=True, help_text='The optional 4 digit ZIP+4 extension for this property', max_length=4, null=True)),
                ('mls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesnacksweb.MLS')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date_added', models.DateTimeField(auto_now_add=True, default='2015-01-01')),
                ('date_updated', models.DateTimeField(auto_now=True, default='2015-01-01')),
                ('agent_email', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_id', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_listing_office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bathrooms_full', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('bathrooms_half', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('bathrooms_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bedrooms_full', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('bedrooms_half', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('bedrooms_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_on_market', models.PositiveIntegerField(blank=True, null=True)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('geo_long', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('list_date', models.DateField(blank=True, default=datetime.date(2015, 1, 1), null=True)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('rooms_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Pending'), (3, 'Sold'), (4, 'Off Market')], default=1, help_text='For sale / sold status of the property', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('agent_listing_office_email', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_listing_office_id', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_listing_office_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_listing_office_phone_2', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_listing_office_url', models.URLField(blank=True, null=True)),
                ('agent_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_phone_2', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'PropertiesCurrent',
            },
        ),
        migrations.AlterModelOptions(
            name='mls',
            options={'verbose_name_plural': 'MLSs'},
        ),
        migrations.CreateModel(
            name='DataCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1_prep_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step2_download_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step3_convert_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step4_pagegen_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step5_cleanup_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('last_step_completed', models.PositiveSmallIntegerField(default=0)),
                ('data_cycle_start', models.DateTimeField(blank=True, null=True)),
                ('data_cycle_finish', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataCycleStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.PositiveSmallIntegerField(choices=[(1, 'Prepare data cycle with pre-download steps'), (2, 'Download/extract all real estate data & media'), (3, 'Normalize all downloaded data into tables'), (4, 'Generate all front-end pages and assets'), (5, 'Finish post-processing cleanup tasks')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('step_status', models.PositiveSmallIntegerField(choices=[(1, 'Not Started'), (2, 'Running'), (3, 'Finished'), (4, 'Finished with errors'), (5, 'Abended/Aborted')], default=1)),
                ('step_start', models.DateTimeField(blank=True, null=True)),
                ('step_finish', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesnacksweb.DataCycle')),
                ('notes', models.TextField(blank=True, help_text='Optional data cycle notes about this step.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rets_city_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date_added', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 26, 20, 38, 10, 577984, tzinfo=utc))),
                ('date_updated', models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 26, 20, 38, 19, 935319, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AddField(
            model_name='datacycle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datacyclestep',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='data_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homesnacksweb.DataCycle'),
        ),
        migrations.AlterUniqueTogether(
            name='propertycurrent',
            unique_together=set([('mls', 'mls_property_id')]),
        ),
    ]
