# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0001_squashed_0012_auto_20160203_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertycurrent',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertycurrent',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
