# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0002_auto_20160203_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='mls',
            name='logo_path',
            field=models.CharField(blank=True, help_text="Filepath to this MLS's logo", max_length=250, null=True),
        ),
    ]
