# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0003_mls_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='property_count_current',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'state')]),
        ),
    ]
