# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0004_auto_20160307_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
