# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0005_city_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='seo_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
