# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 17:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0006_propertycurrent_seo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='house_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertycurrent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Pending'), (3, 'Sold'), (4, 'Off Market'), (9, 'Hidden')], default=1, help_text='For sale / sold status of the property', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
