# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0007_auto_20160126_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_listing_office_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_listing_office_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_listing_office_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_listing_office_phone_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_listing_office_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_phone_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
