# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0008_auto_20160312_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='property_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='sewer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='total_rooms',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='water_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
