# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0009_auto_20160313_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='family_room_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
