# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0010_propertycurrent_family_room_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycurrent',
            name='family_room_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
