# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0011_auto_20160314_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='bedroom_dimensions_all',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertycurrent',
            name='bathrooms_full',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertycurrent',
            name='bathrooms_half',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
