# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0012_auto_20160314_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='living_room_dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='living_room_flooring',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='living_room_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
