# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0013_auto_20160314_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='attic_info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='basement_info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
