# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0015_auto_20160315_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='fireplace_info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='garage_info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
