# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0016_auto_20160315_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='exterior_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
