# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0017_propertycurrent_exterior_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='foundation_info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='lot_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='lot_dimensions',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='roof_info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
