# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0018_auto_20160315_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='school_elementary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='school_high',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='school_middle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
