# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0019_auto_20160315_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycurrent',
            name='agent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
