# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesnacksweb', '0020_auto_20160317_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_listing_office_address_1',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='propertycurrent',
            name='agent_listing_office_address_citystzip',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
